Portafolio/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('portfolio.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import post_detail, render_posts

app_name='blog'

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail'),
]

portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]


blog/models.py
from django.db import models
import datetime
# Create your models here.

class Post(models.Model):
    title=models.CharField(max_length=100)
    description=models.TextField()
    image=models.ImageField(upload_to='blog/images')
    date=models.DateField(datetime.date.today)

    class Meta:
        verbose_name="post"
        verbose_name_plural="posts"

portfolio/models.py
from django.db import models
# Create your models here.

class Project(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=250)
    image=models.ImageField(upload_to='portfolio/images')
    url=models.URLField(blank=True)

    class Meta:
        verbose_name="project"
        verbose_name_plural="projects"

blog/views.py
from django.shortcuts import render,get_object_or_404

from blog.models import Post

# Create your views here.
def render_posts(request):
    posts=Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})


def post_detail(request, post_id):
    post=get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {'posts': post})

portfolio/views.py
from django.shortcuts import render
from portfolio.models import Project


# Create your views here.
def home(request):
    projects=Project.objects.all()
    return render(request, 'home.html', {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}

<div class="text-center">
    
    <h2>{{posts.title}}</h2>


    <h3 class="my-2 h5 text-muted">{{posts.date|date:'F jS Y'}}</h3>

    <img class="img-fluid" src="{{posts.image.url}}" alt="{{posts.title}}">

    <div class="my-4">
        <p>{{posts.description|safe}}</p>
    </div>


</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
{% block content %}
<h1>Post</h1>

{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>
            <div class="col-9">
    
                <h2>{{post.title}}</h2>
    
                <p>{{post.description|striptags|truncatechars:100 }}</p>
                <h5>{{post.date|date:'M d Y'|upper}}</h5>
                
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div>
    
    
    </div>
    
</div>

{% endfor %}
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}

<header class="row bg bg-black">
    <div class="col-md-4 my-auto">
        <img style="width: 30vw;" src="{% static 'Portafolio/img/profile.jpg' %}">
    </div>

    <div class="col-md-8 my-auto" style="padding-left: 4rem;">
        <h1>I am <strong>Ferricty</strong></h1>
        <h3> I am Python FullStack Developer</h3>
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis 
        consectetur tempora placeat voluptate esse est non ex earum eos excepturi ea eaque quia, 
        expedita aperiam minus quasi magni, mollitia maiores explicabo repellendus accusantium 
        consequuntur aspernatur! Facilis ut cumque nulla aut fugiat! Laborum id ea dolore ipsam, 
        ducimus temporibus reiciendis sed aperiam nemo in molestias et aliquam minus ullam? Aspernatur
        aut ratione fugiat. At, inventore dignissimos temporibus earum esse expedita reprehenderit 
        nam provident nisi excepturi aliquid harum obcaecati. Quod, rerum quibusdam in fugit ad 
        dolores autem numquam</p>

        <a href="{% static 'Portafolio/img/CV.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3" style="border: solid aquamarine">
            Download CV</a>
    </div>
</header>



<div class="row my-4 text-center">
    <h3>My Projects</h3>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati, quibusdam?</p>
{% for project in projects %}

<div class="col-md-4">
    <div class="card bg-black card-project">
        <img src="{{project.image.url}}" alt="{{project.title}}"class="card img-top">
        <div class="card-body">

        <h2>{{project.title}}</h2><p>{{project.description}}</p>
        
        
        {% if project.url %}
            <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
        {% endif %}
        </div>
    </div>
</div>

    
{% endfor %}
    

{% endblock %}
</div>

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    
    <link href="{% static 'Portafolio/vendor/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'Portafolio/vendor/css/navbar.css' %}" rel="stylesheet">
    <script src="{% static 'Portafolio/vendor/js/bootstrap.bundle.min.js' %}"></script>
    <title>Django Portafolio</title>
</head>
<body class="text-light">
    

    {% include 'partials/navbar.html' %}


    <div class="container p-4"> 

    {% block content %}

    {% endblock %}



</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark bg-black" aria-label="Fourth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand fw-bold fst-italic" style="padding-left: 3rem;" href="/">Ferricty</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarsExample04">
        <ul class="navbar-nav ms-auto">
            <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
            </li>
            <li class="nav-item d-flex align-items-center"  style="padding-right: 10rem;">
                <a class="btn btn-primary btn-sm" href="{% static 'Portafolio/img/CV.pdf' %}" target="_blank">Download CV</a>
            </li>
            <!--
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
            <ul class="dropdown-menu" aria-labelledby="dropdown04">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
            </li>-->
        </ul>
        <!--<form role="search" >
            <input class="form-control" type="search" placeholder="Search" aria-label="Search">
        </form>-->
        </div>
    </div>
</nav>

